#pragma once
/** DBO object that represents a report generated by finding transactions with certain tags over a certain period
 */

#include <Wt/Dbo/Dbo>
#include <Wt/WDate>
#include <Wt/WString>

#include <string>

#include <string>

namespace docucount {
namespace dbo {

struct Tag;

struct Transaction : public Wt::Dbo::Dbo<Cat> {
    Wt::WString name;
    bool withNeg{true}; /// Include negative value transactions in the report
    bool withPos{true}; /// Include positive value transactions in the report
    Wt::WDate firstDay; /// Will include transactions starting on this day
    Wt::WDate dayAfter; /// Will include transactions up to the day before this day. Eg. if this value is Nov 1, we will include transactions up to Oct 31st

    Wt::Dbo::collection<Tag> tags;
    void persist(Action& a) {
        using Wt::Dbo::field;

        field(a, name, "name");
        field(a, withNeg, "withNeg");
        field(a, withPos, "withPos");
        field(a, firstDay, "firstDay");
        field(a, dayAfter, "dayAfter");
        Wt::Dbo::hasMany(a, tags, dbo::ManyToMany, "report_tag");
    }
};

}
}
